services:
  - type: web
    name: email-automation
    env: python
    buildCommand: |
      pip install -r backend/requirements.txt && 
      cd frontend && 
      echo "VITE_API_URL=$VITE_API_URL" > .env && 
      npm install framer-motion &&
      npm install && 
      npm run build
    startCommand: gunicorn --chdir backend 'app:app'
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: FLASK_ENV
        value: production
      - key: VITE_API_URL
        value: https://eply.onrender.com